export const API_ERROR_CODES = {
    INVALID_QUERY: "INVALID_QUERY",

    CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
    SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",
    CHAPTER_NOT_FOUND: "CHAPTER_NOT_FOUND",

    NOTE_NOT_FOUND: "NOTE_NOT_FOUND",
    VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
    QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",

    INVALID_ID: "INVALID_ID",

    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
} as const;